GET http://localhost:8080/orders/

### send post
POST http://localhost:8080/orders
Content-Type: application/json

{
  "customer_name": "endo",
  "items": [
    {
      "item_code": "SBN2",
      "description": "MANGA koi to uso",
      "quantity": 3
    }, {
      "item_code": "SBN2",
      "description": "MANGA bloom into you",
      "quantity":5
    }
  ]
}


### DELETE
DELETE http://localhost:8080/orders/1